"""songs table

Revision ID: 4d238dec0fa4
Revises: 
Create Date: 2019-12-13 16:19:46.842465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d238dec0fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('artist', sa.String(length=120), nullable=True),
    sa.Column('song', sa.String(length=120), nullable=False),
    sa.Column('youtube', sa.String(length=120), nullable=True),
    sa.Column('answer', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('song')
    )
    op.create_index(op.f('ix_answer_answer'), 'answer', ['answer'], unique=True)
    op.create_index(op.f('ix_answer_artist'), 'answer', ['artist'], unique=True)
    op.create_index(op.f('ix_answer_difficulty'), 'answer', ['difficulty'], unique=False)
    op.create_index(op.f('ix_answer_song'), 'answer', ['song'], unique=False)
    op.create_index(op.f('ix_answer_time'), 'answer', ['time'], unique=False)
    op.create_index(op.f('ix_answer_youtube'), 'answer', ['youtube'], unique=True)
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=120), nullable=True),
    sa.Column('song', sa.String(length=120), nullable=True),
    sa.Column('youtube', sa.String(length=120), nullable=True),
    sa.Column('answer', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_answer'), 'song', ['answer'], unique=True)
    op.create_index(op.f('ix_song_artist'), 'song', ['artist'], unique=True)
    op.create_index(op.f('ix_song_difficulty'), 'song', ['difficulty'], unique=False)
    op.create_index(op.f('ix_song_song'), 'song', ['song'], unique=True)
    op.create_index(op.f('ix_song_time'), 'song', ['time'], unique=False)
    op.create_index(op.f('ix_song_youtube'), 'song', ['youtube'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_youtube'), table_name='song')
    op.drop_index(op.f('ix_song_time'), table_name='song')
    op.drop_index(op.f('ix_song_song'), table_name='song')
    op.drop_index(op.f('ix_song_difficulty'), table_name='song')
    op.drop_index(op.f('ix_song_artist'), table_name='song')
    op.drop_index(op.f('ix_song_answer'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_answer_youtube'), table_name='answer')
    op.drop_index(op.f('ix_answer_time'), table_name='answer')
    op.drop_index(op.f('ix_answer_song'), table_name='answer')
    op.drop_index(op.f('ix_answer_difficulty'), table_name='answer')
    op.drop_index(op.f('ix_answer_artist'), table_name='answer')
    op.drop_index(op.f('ix_answer_answer'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
