"""empty message

Revision ID: a9bddabfc4b3
Revises: f96ad5c27e43
Create Date: 2020-01-30 17:16:42.554290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bddabfc4b3'
down_revision = 'f96ad5c27e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=40), nullable=True),
    sa.Column('song_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('times', sa.String(length=20), nullable=True),
    sa.Column('throughout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_song_name'), ['song_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_throughout'), ['throughout'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_times'), ['times'], unique=False)

    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=40), nullable=True),
    sa.Column('song_name', sa.String(length=65), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('answers', sa.String(length=1000), nullable=True),
    sa.Column('times', sa.String(length=20), nullable=True),
    sa.Column('throughout', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_song_name'), ['song_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_throughout'), ['throughout'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_times'), ['times'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_times'))
        batch_op.drop_index(batch_op.f('ix_answer_throughout'))
        batch_op.drop_index(batch_op.f('ix_answer_source_type'))
        batch_op.drop_index(batch_op.f('ix_answer_source'))
        batch_op.drop_index(batch_op.f('ix_answer_song_name'))
        batch_op.drop_index(batch_op.f('ix_answer_artist'))

    op.drop_table('answer')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_times'))
        batch_op.drop_index(batch_op.f('ix_song_throughout'))
        batch_op.drop_index(batch_op.f('ix_song_source_type'))
        batch_op.drop_index(batch_op.f('ix_song_source'))
        batch_op.drop_index(batch_op.f('ix_song_song_name'))
        batch_op.drop_index(batch_op.f('ix_song_artist'))

    op.drop_table('song')
    # ### end Alembic commands ###
